### ISSUE TITLE
Minutes of Meeting | 20.11.26

### ISSUE THREAD

**Issue by Reichidad** [Reichidad/Team-Monday-Capstone#12]
# TODO until the final announcement
  - [x] Configure communication with deep learning model server
  - [x] Apply 3d depth to tattoos in android
  - [x] Server load test
